workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push" # avoids duplicate pipelines when a merge request is open
      when: never
    - if: $CI_COMMIT_BRANCH == null || $CI_OPEN_MERGE_REQUESTS == null || $CI_PIPELINE_SOURCE != "push"

variables:
  ALPINE: "alpine"

default:
  image: eclipse-temurin:17.0.13_11-jdk

stages:
  - build
  - test
  - push
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000" && $CI_PIPELINE_SOURCE == "push" # first statement evaluates as true for first pipeline run on a new branch, and for merge requests
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - app/**/*
          - buildSrc/**/*
          - job/**/*
    - if: $CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" || $CI_PIPELINE_SOURCE != "push"
      changes:
        paths:
          - app/**/*
          - buildSrc/**/*
          - job/**/*
  tags:
    - dockersocket
  script:
    - ./gradlew assemble --parallel
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000" && $CI_PIPELINE_SOURCE == "push" # first statement evaluates as true for first pipeline run on a new branch, and for merge requests
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - app/**/*
          - buildSrc/**/*
    - if: $CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" || $CI_PIPELINE_SOURCE != "push"
      changes:
        paths:
          - app/**/*
          - buildSrc/**/*
  dependencies:
    - build
  tags:
    - privileged
  script:
    - ./gradlew check --parallel
  artifacts:
    when: always
    reports:
      junit: app/*/**/TEST-*.xml

pushLoriAppImage:
  stage: push
  needs:
    - job: test
      optional: true
  dependencies:
    - test
  tags:
    - dockersocket
  rules:
    # Run automatically after merge on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      changes:
        - app/lori/**/*
      when: on_success

    # Show as manual during merge request pipeline
    - if: $CI_OPEN_MERGE_REQUESTS
      when: manual
      allow_failure: true

    # Default fallback: don’t run
    - when: never
  script:
    - ./gradlew :app:lori:server:jibBuildTar
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_IMAGEPUSHER"
    - base64 -d "$SSH_PRIVATE_KEY_IMAGEPUSHER" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$SSH_KNOWN_HOSTS_QS" "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp app/lori/server/build/jib-image.tar imagepusher@lori-prod.dmz3.zbw.eu:/var/tmp/lori_${CI_COMMIT_SHORT_SHA}.tar
    - |
      echo CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH
      echo CI_DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
      echo CI_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      echo CI_MERGE_REQUEST_TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      echo CI_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        scp app/lori/server/build/jib-image.tar imagepusher@lori-prod.dmz3.zbw.eu:/var/tmp/lori_${CI_COMMIT_SHORT_SHA}.tar
      else
        echo "Skipping production deploy: commit not merged to default branch"
      fi
    - scp app/lori/server/build/jib-image.tar imagepusher@lori-qs.dmz3.zbw.eu:/var/tmp/lori_${CI_COMMIT_SHORT_SHA}.tar
    - ssh-agent -k

pushLoriRefreshMaterializedViewsJobImage:
  stage: push
  needs:
    - job: test
      optional: true
  rules:
    - changes:
        - job/refresh_materialized_views/**/*
  dependencies:
    - test
  tags:
    - dockersocket
  script:
    - ./gradlew :job:refresh_materialized_views:jibBuildTar
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_IMAGEPUSHER"
    - base64 -d "$SSH_PRIVATE_KEY_IMAGEPUSHER" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$SSH_KNOWN_HOSTS_QS" "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        scp job/refresh_materialized_views/build/jib-image.tar imagepusher@lori-prod.dmz3.zbw.eu:/var/tmp/refresh_materialized_views_${CI_COMMIT_SHORT_SHA}.tar
      else
        echo "Skipping production deploy: commit not merged to default branch"
      fi
    - scp job/refresh_materialized_views/build/jib-image.tar imagepusher@lori-qs.dmz3.zbw.eu:/var/tmp/refresh_materialized_views_${CI_COMMIT_SHORT_SHA}.tar


pushLoriImportJobImage:
  stage: push
  needs:
    - job: test
      optional: true
  rules:
    - changes:
      - job/lori_import/**/*
  dependencies:
    - test
  tags:
    - dockersocket
  script:
    - ./gradlew :job:lori_import:jibBuildTar
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_IMAGEPUSHER"
    - base64 -d "$SSH_PRIVATE_KEY_IMAGEPUSHER" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$SSH_KNOWN_HOSTS_QS" "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        scp job/lori_import/build/jib-image.tar imagepusher@lori-prod.dmz3.zbw.eu:/var/tmp/lori_import_${CI_COMMIT_SHORT_SHA}.tar
      else
        echo "Skipping production deploy: commit not merged to default branch"
      fi
    - scp job/lori_import/build/jib-image.tar imagepusher@lori-qs.dmz3.zbw.eu:/var/tmp/lori_import_${CI_COMMIT_SHORT_SHA}.tar

pushTemplateApplyJobImage:
  stage: push
  needs:
    - job: test
      optional: true
  rules:
    - changes:
      - job/template_apply/**/*
  dependencies:
    - test
  tags:
    - dockersocket
  script:
    - ./gradlew :job:template_apply:jibBuildTar
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_IMAGEPUSHER"
    - base64 -d "$SSH_PRIVATE_KEY_IMAGEPUSHER" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$SSH_KNOWN_HOSTS_QS" "$SSH_KNOWN_HOSTS_PROD" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        scp job/template_apply/build/jib-image.tar imagepusher@lori-prod.dmz3.zbw.eu:/var/tmp/template_apply_${CI_COMMIT_SHORT_SHA}.tar
      else
        echo "Skipping production deploy: commit not merged to default branch"
      fi
    - scp job/template_apply/build/jib-image.tar imagepusher@lori-qs.dmz3.zbw.eu:/var/tmp/template_apply_${CI_COMMIT_SHORT_SHA}.tar

deployToQs:
  stage: deploy
  needs:
    - job : "pushLoriAppImage"
      optional: true
  environment: qs
  image:
    name: $ALPINE
  rules:
    # Manual step only on main branch after merge
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true

    # Manual step during merge request pipeline
    - if: $CI_OPEN_MERGE_REQUESTS
      when: manual
      allow_failure: true

    # Default fallback: don’t run
    - when: never
  script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_DOCKER_QS"
    - base64 -d "$SSH_PRIVATE_KEY_DOCKER_QS" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS_QS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      ssh docker@lori-qs.dmz3.zbw.eu /bin/bash -s << EOT
      docker load --input /var/tmp/lori_${CI_COMMIT_SHORT_SHA}.tar && \
      sed -i "s/app-lori-server:[0-9a-zA-Z_.-]*/app-lori-server:${CI_COMMIT_SHA:0:12}/g" /srv/lori/config-qs/docker-compose-qs.yaml && \
      docker compose -f /srv/lori/docker-compose.yaml --profile "*" down --remove-orphans
      docker compose -f /srv/lori/docker-compose.yaml up -d
      docker container prune --filter "until=100h" -f
      docker ps
      EOT

deployToProd:
  stage: deploy
  when: manual
  needs:
    - job : "pushLoriAppImage"
      optional: true
  environment: production
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - app/lori/**/*
  image:
    name: $ALPINE
  script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_DOCKER_PROD"
    - base64 -d "$SSH_PRIVATE_KEY_DOCKER_PROD" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS_PROD" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      ssh docker@lori-prod.dmz3.zbw.eu /bin/bash -s << EOT
      docker load --input /var/tmp/lori_${CI_COMMIT_SHORT_SHA}.tar && \
      sed -i "s/app-lori-server:[0-9a-zA-Z_.-]*/app-lori-server:${CI_COMMIT_SHA:0:12}/g" /srv/lori/config-prod/docker-compose-prod.yaml && \
      docker compose -f /srv/lori/docker-compose.yaml --profile "*" down --remove-orphans
      docker compose -f /srv/lori/docker-compose.yaml up -d
      docker ps
      EOT

.deploy_docker_job_template:
  stage: deploy
  when: manual
  image:
    name: $ALPINE
  script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - base64 -d "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - |
      ssh "docker@${SSH_HOST}" /bin/bash -s << EOT
      set -euo pipefail

      docker load --input "/var/tmp/${JOB_IMAGE_TAR_PREFIX}_${CI_COMMIT_SHORT_SHA}.tar"

      sed -i "s/${JOB_IMAGE_NAME}:[0-9a-zA-Z_.-]*/${JOB_IMAGE_NAME}:${CI_COMMIT_SHA:0:12}/g" "${DOCKER_COMPOSE_ENV_FILE}"

      if [ "${DOCKER_COMPOSE_DOWN_BEFORE_UP:-false}" = "true" ]; then
        docker compose -f /srv/lori/docker-compose.yaml down --remove-orphans
      fi

      docker compose -f /srv/lori/docker-compose.yaml --profile "${DOCKER_COMPOSE_PROFILE}" up -d
      docker ps
      EOT

.deploy_qs:
  extends: .deploy_docker_job_template
  environment: qs
  variables:
    SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY_DOCKER_QS"
    SSH_KNOWN_HOSTS: "$SSH_KNOWN_HOSTS_QS"
    SSH_HOST: "lori-qs.dmz3.zbw.eu"
    DOCKER_COMPOSE_ENV_FILE: "/srv/lori/config-qs/docker-compose-qs.yaml"
    DOCKER_COMPOSE_DOWN_BEFORE_UP: "false"
  rules:
    - changes:
        - $JOB_CHANGES_PATH
    # Manual step only on main branch after merge
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
    # Manual step during merge request pipeline
    - if: $CI_OPEN_MERGE_REQUESTS
      when: manual
      allow_failure: true
    # Default fallback: don’t run
    - when: never

.deploy_prod:
  extends: .deploy_docker_job_template
  environment: production
  variables:
    SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY_DOCKER_PROD"
    SSH_KNOWN_HOSTS: "$SSH_KNOWN_HOSTS_PROD"
    SSH_HOST: "lori-prod.dmz3.zbw.eu"
    DOCKER_COMPOSE_ENV_FILE: "/srv/lori/config-prod/docker-compose-prod.yaml"
    DOCKER_COMPOSE_DOWN_BEFORE_UP: "true"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $JOB_CHANGES_PATH

deployRefreshMaterializedViewsToQs:
  extends: .deploy_qs
  needs:
    - job: "pushLoriRefreshMaterializedViewsJobImage"
      optional: true
  variables:
    JOB_CHANGES_PATH: "job/refresh_materialized_views/**/*"
    JOB_IMAGE_TAR_PREFIX: "refresh_materialized_views"
    JOB_IMAGE_NAME: "job-refresh_materialized_views"
    DOCKER_COMPOSE_PROFILE: "cronjob-refresh-materialized-views"

deployRefreshMaterializedViewsToProd:
  extends: .deploy_prod
  needs: ["pushLoriRefreshMaterializedViewsJobImage"]
  variables:
    JOB_CHANGES_PATH: "job/refresh_materialized_views/**/*"
    JOB_IMAGE_TAR_PREFIX: "refresh_materialized_views"
    JOB_IMAGE_NAME: "job-refresh_materialized_views"
    DOCKER_COMPOSE_PROFILE: "cronjob-refresh-materialized-views"

deployImportJobToQs:
  extends: .deploy_qs
  needs:
    - job: "pushLoriImportJobImage"
      optional: true
  variables:
    JOB_CHANGES_PATH: "job/lori_import/**/*"
    JOB_IMAGE_TAR_PREFIX: "lori_import"
    JOB_IMAGE_NAME: "job-lori_import"
    DOCKER_COMPOSE_PROFILE: "cronjob-loriimport"

deployImportJobToProd:
  extends: .deploy_prod
  needs: ["pushLoriImportJobImage"]
  variables:
    JOB_CHANGES_PATH: "job/lori_import/**/*"
    JOB_IMAGE_TAR_PREFIX: "lori_import"
    JOB_IMAGE_NAME: "job-lori_import"
    DOCKER_COMPOSE_PROFILE: "cronjob-loriimport"

deployTemplateApplyJobToQs:
  extends: .deploy_qs
  needs:
    - job: "pushTemplateApplyJobImage"
      optional: true
  variables:
    JOB_CHANGES_PATH: "job/template_apply/**/*"
    JOB_IMAGE_TAR_PREFIX: "template_apply"
    JOB_IMAGE_NAME: "job-template_apply"
    DOCKER_COMPOSE_PROFILE: "cronjob-template-apply"

deployTemplateApplyJobToProd:
  extends: .deploy_prod
  needs: ["pushTemplateApplyJobImage"]
  variables:
    JOB_CHANGES_PATH: "job/template_apply/**/*"
    JOB_IMAGE_TAR_PREFIX: "template_apply"
    JOB_IMAGE_NAME: "job-template_apply"
    DOCKER_COMPOSE_PROFILE: "cronjob-template-apply"
