rootProject.name = "zbwcloud"
include("app:access:api")
include("app:access:client")
include("app:access:server")
include("app:access:server:ui")
include("app:auth:api")
include("app:auth:client")
include("app:auth:server")
include("app:handle:api")
include("app:handle:client")
include("app:handle:server")
include("app:helloworld:api")
include("app:helloworld:client")
include("app:helloworld:server")
include("app:helloworld:server:ui")
