rootProject.name = "zbwcloud"
include("app:auth:api")
include("app:auth:client")
include("app:auth:server")
include("app:handle:api")
include("app:handle:client")
include("app:handle:server")
include("app:lori:api")
include("app:lori:client")
include("app:lori:server")
include("app:lori:server:ui")
include("job:lori_import")
